name: agriapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_auth: ^4.3.0
  firebase_messaging: ^14.2.1
  flutter_countdown_timer: ^4.1.0
  intl: ^0.17.0
  uuid: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/main.svg


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 800

